alias p='git add . && git commit -m "update" && git push'
alias t='git add . && git commit -m "update" && git push'
alias t='git add . && git commit -m "update" && git push -u origin main -f'
alias t='git add . && git commit -m "update" && git push -u origin main -f'
alias phim='git pull --rebase origin main && git push origin main'
alias phim='git pull --rebase origin main && git push origin main'
alias phim='git pull --rebase origin main && git push origin main'
alias y='git pull --rebase origin main && git push origin main'
